jobs:
  - job: "${{ parameters.name }}"
    strategy:
      matrix:
        linux:
          imageName: "ubuntu-16.04"
        mac:
          imageName: "macos-10.13"
        windows:
          imageName: "vs2017-win2016"
    displayName: "${{ parameters.name }}"
    pool:
      vmImage: $(imageName)

    steps:
      - task: NodeTool@0
        displayName: "Use Node ${{ parameters.nodeVersion }}"
        inputs:
          versionSpec: ${{ parameters.nodeVersion }}

      - bash: |
          set -e

          npm ci
          npm run compile
          npm run test:coverage  # linting is run as part of pretest
        displayName: "Run tests"

      - ${{ if eq(parameters.nodeVersion, '8.16.1') }}:
          - bash: |
              set -e

              token=$(CODECOV_TOKEN)
              if [[ -z "${token}" ]]; then
                echo "Need to set CODECOV_TOKEN"
                exit 1
              fi

              # https://docs.codecov.io/docs/about-the-codecov-bash-uploader
              bash <(curl -s https://codecov.io/bash) -t ${token}
            displayName: "Upload code coverage report"
            env:
              CODECOV_TOKEN: $(CODECOV_TOKEN)
            condition: eq(variables['imageName'], 'ubuntu-16.04')
