service: nd10-win-web

provider:
  name: azure
  prefix: tmp
  stage: qa
  region: West Europe
  runtime: nodejs10
  os: windows
  apim: true

  environment:
    VARIABLE_FOO: 'foo'

plugins:
  - serverless-azure-functions

package:
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  hello:
    handler: hello.sayHello
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous

 