export const constants = {
  bindings: "bindings",
  settings: "settings",
  name: "name",
  displayName: "displayName",
  type: "type",
  direction: "direction",
  trigger: "Trigger",
  inDirection: "in",
  outDirection: "out",
  value: "value",
  resource: "resource",
  required: "required",
  storage: "storage",
  connection: "connection",
  enum: "enum",
  defaultValue: "defaultValue",
  webHookType: "webHookType",
  httpTrigger: "httpTrigger",
  queue: "queue",
  queueName: "queueName",
  xAzureSettings: "x-azure-settings",
  entryPoint: "entryPoint",
  variableKeys: {
    config: "serverlessAzureConfig",
    subscriptionId: "subscriptionId",
    tenantId: "tenantId",
    appId: "appId",
    packageTimestamp: "packageTimestamp",
    azureCredentials: "azureCredentials",
  }
}
