# CI should only run when PRs are opened against dev/master.
trigger:
  - master
  - dev

pr:
  - master
  - dev

variables:
- group: coveralls-credentials  # variable group

jobs:
- template: templates/unit-tests.yml
  parameters:
    nodeVersion: 6

- template: templates/unit-tests.yml  # path relative to this file
  parameters:
    nodeVersion: 8

- template: templates/unit-tests.yml
  parameters:
    nodeVersion: 10
