# CI should only run when PRs are opened against dev/master.
pr:
  - master
  - dev

pool:
  vmImage: 'ubuntu-16.04'

jobs:
- template: pipelines/templates/unit-tests.yml
  parameters:
    nodeVersion: 8.x

- template: pipelines/templates/unit-tests.yml
  parameters:
    nodeVersion: 10.x
