# CI should only run when PRs are opened against dev/master.
trigger: none
pr:
  - master
  - dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- task: Bash@3
  displayName: 'Build serverless-azure-functions'
  inputs:
    targetType: filePath
    filePath: ./scripts/build.sh

- task: Bash@3
  displayName: 'Run coverage'
  script: |
    npm run test:coverage
    cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
