service: csharp31-linux

provider:
  name: azure
  runtime: dotnet3.1
  region: West Europe
  prefix: tmp
  stage: qa
  os: linux
  apim: true

plugins:
  - serverless-azure-functions

functions:
  Hello:
    handler: hello
    events:
      - http: true
        methods:
          - GET
        authLevel: anonymous