service: dt31-lin

provider:
  name: azure
  runtime: dotnet3.1
  region: West Europe
  prefix: tmp
  stage: qa
  os: linux
  apim: true
  environment:
    VARIABLE_FOO: 'foo'

plugins:
  - serverless-azure-functions

package:
  exclude:
    - local.settings.json
    - .vscode/**
    - node_modules/**
    - .funcignore
    - package.json
    - package-lock.json
    - data.json

functions:
  hello:
    handler: hello
    events:
      - http: true
        methods:
          - GET
        authLevel: anonymous