on:
  schedule:
    # Run twice per day (3:00 AM & 3:00 PM)
    - cron: '0 3/15 * * *'
  push:
    branches:
      # Push to a branch that ends with "/trigger-int-tests" to manually trigger tests
      - '**/python-int-tests'
name: Python Integration Tests
jobs:
  int_tests_python:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [ python36, python37, python38 ]
    steps:
    - uses: actions/checkout@master
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: npm install
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: npm install
    - name: build
      run: tsc
    - name: package, deploy, invoke, remove
      run: npm run test:int -- -t deploy.* -d ${{ matrix.runtime }}
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID}}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET}}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID}}
  