on:
  schedule:
    # Run twice per day (12:45 AM & PM)
    - cron: '45 */12 * * *'
  push:
    branches:
      # Push to a branch that ends with "/trigger-int-tests" to manually trigger tests
      - '**/trigger-int-tests'
name: Integration Tests
jobs:
  multi_os_integration_tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [dotnet22, dotnet31, node10, node12]
        os: [linux, windows]
    steps:
    - uses: actions/checkout@master
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: npm install
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: npm install
    - name: build
      run: tsc
    - name: setup dotnet 2.2
      if: ${{ matrix.runtime }} == 'dotnet22'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.100'
    - name: setup dotnet 3.1
      if: ${{ matrix.runtime }} == 'dotnet31'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: integration tests ${{ matrix.runtime }}-${{ matrix.os }}
      run: npm run test:int -- -t deploy -d ${{ matrix.runtime }}-${{ matrix.os }}
  int_tests_python:
    name: Test (python, linux)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: npm install
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: npm install
    - name: build
      run: tsc
    - name: python integration tests
      run: npm run test:int -- -t deploy -d python
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID}}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET}}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID}}
  