on:
  schedule:
    # Run twice per day (2:00 AM & 2:00 PM)
    - cron: '0 2/14 * * *'
  push:
    branches:
      # Push to a branch that ends with "/trigger-int-tests" to manually trigger tests
      - '**/node-int-tests'
name: Node Integration Tests
jobs:
  multi_os_integration_tests:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [ node10, node12 ]
        os: [ linux, windows ]
      fail-fast: false
    steps:
    - uses: actions/checkout@master
    
    # Install dependencies and cache them
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - name: npm install
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: npm install
    
    # Build plugin
    - name: build
      run: tsc
    
    # Run the integration test
    - name: package, deploy, invoke, remove
      run: npm run test:int -- -t deploy.* -d '${{ matrix.runtime }}-${{ matrix.os }}(-webpack)?'
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID}}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET}}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID}}
  